"""Theme cache — machine-local DERIVED store for behavioral/conceptual themes.

ADR-014 (rebuildable derived indexes): themes are NOT a new column on the synced
``nodes`` table — in-place mutations of synced rows do not propagate cross-machine
(the additive union is INSERT-OR-IGNORE), and a new synced column is new sync
surface. Themes are instead a local cache keyed by ``(node_id, content_sha)``,
regenerated by ``scripts/theme_backfill.py`` and invalidated automatically when a
node's content changes. Each machine pays its own (cheap) backfill; zero new sync
surface. The semantic embedding path prepends the theme line to a node's embedded
text so abstract behavioral queries bridge to concrete nodes (the 2026-06-11
embedder bake-off: bge-small + theme lines bridges 4/5 dead queries vs 2/5 alone).

Stored beside the embeddings cache at ``<data_dir>/cache/themes.sqlite``.
"""

from __future__ import annotations

import hashlib
import sqlite3
from datetime import datetime, timezone
from pathlib import Path


def content_sha(content: str) -> str:
    """Full SHA-256 of the raw node content — the theme-cache validity key.

    Full-width (not the 16-hex node-id hash) and over RAW content: any content
    change, however small, must invalidate the derived theme so the embedder
    never silently mixes a stale theme with edited content.
    """
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


class ThemeCache:
    """SQLite-backed ``node_id → {content_sha, themes, model, created_at}`` store."""

    def __init__(self, path: str | Path) -> None:
        self._path = Path(path)
        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._conn = sqlite3.connect(str(self._path))
        self._conn.row_factory = sqlite3.Row
        self._conn.execute(
            """
            CREATE TABLE IF NOT EXISTS themes (
                node_id     TEXT PRIMARY KEY,
                content_sha TEXT NOT NULL,
                themes      TEXT NOT NULL,
                model       TEXT NOT NULL,
                created_at  TEXT NOT NULL
            )
            """
        )
        self._conn.commit()

    def get(self, node_id: str) -> dict | None:
        """Return the stored record for ``node_id`` (any sha), or None."""
        row = self._conn.execute(
            "SELECT node_id, content_sha, themes, model, created_at FROM themes WHERE node_id = ?",
            (node_id,),
        ).fetchone()
        return dict(row) if row else None

    def get_valid(self, node_id: str, sha: str) -> str | None:
        """Return the theme text iff a record exists AND its sha matches.

        A stored theme whose ``content_sha`` differs from ``sha`` is stale (the
        node's content changed) and is treated as missing — lazy invalidation.
        """
        row = self._conn.execute(
            "SELECT themes FROM themes WHERE node_id = ? AND content_sha = ?",
            (node_id, sha),
        ).fetchone()
        return row["themes"] if row else None

    def has_valid(self, node_id: str, sha: str) -> bool:
        """True if a sha-matching theme exists for ``node_id`` (resumability)."""
        return (
            self._conn.execute(
                "SELECT 1 FROM themes WHERE node_id = ? AND content_sha = ?",
                (node_id, sha),
            ).fetchone()
            is not None
        )

    def put(
        self,
        node_id: str,
        sha: str,
        themes: str,
        model: str,
        created_at: str | None = None,
    ) -> None:
        """Upsert a theme record for ``node_id`` (replaces any prior sha)."""
        ts = created_at or datetime.now(timezone.utc).isoformat()
        self._conn.execute(
            "INSERT OR REPLACE INTO themes "
            "(node_id, content_sha, themes, model, created_at) VALUES (?, ?, ?, ?, ?)",
            (node_id, sha, themes, model, ts),
        )
        self._conn.commit()

    def count(self) -> int:
        return self._conn.execute("SELECT COUNT(*) FROM themes").fetchone()[0]

    def close(self) -> None:
        self._conn.close()


# ── Module-level singleton ─────────────────────────────────────────────
_cache: ThemeCache | None = None


def get_theme_cache() -> ThemeCache:
    """Get or create the global theme cache singleton (under cache/themes.sqlite)."""
    global _cache
    if _cache is None:
        from memcp.config import get_config

        _cache = ThemeCache(get_config().cache_dir / "themes.sqlite")
    return _cache


def reset_theme_cache() -> None:
    """Reset the singleton (tests / after a data-dir switch)."""
    global _cache
    if _cache is not None:
        import contextlib

        with contextlib.suppress(Exception):
            _cache.close()
    _cache = None
