"""Phase 4 Item 2 — theme cache + embedding-text composition.

Themes are machine-local DERIVED data (ADR-014): a local cache keyed by
(node_id, content_sha), regenerated by the backfill, invalidated automatically
when content changes. The semantic path embeds ``themes + "\\n" + content[:N]``
when a valid (sha-matching) theme exists, plain content otherwise.

Tests pin the contract:
  3. sha-keyed validity: content change invalidates; missing theme = graceful
     plain-content embed.
  4. composition: with MEMCP_SEMANTIC_RECALL off, behavior is bit-identical to
     phase 3 (flag-off noop preserved); with it on and a theme present, the
     embedded text includes the theme line.
"""

from __future__ import annotations

import pytest

import memcp.config as config_module
from memcp.core.embedding_text import EMBED_CONTENT_CHARS, compose_embedding_text
from memcp.core.theme_cache import ThemeCache, content_sha, get_theme_cache, reset_theme_cache


@pytest.fixture
def env(tmp_path, monkeypatch):
    monkeypatch.setenv("MEMCP_DATA_DIR", str(tmp_path))
    config_module._config = None
    reset_theme_cache()
    yield tmp_path
    config_module._config = None
    reset_theme_cache()


# ── Test 3 — sha-keyed validity ───────────────────────────────────────────────
class TestShaKeyedValidity:
    def test_valid_theme_returned_for_matching_sha(self, env) -> None:
        cache = get_theme_cache()
        content = "Drove the urgent production rollout end to end."
        cache.put("n1", content_sha(content), "theme: shipping under deadline", "haiku")
        assert cache.get_valid("n1", content_sha(content)) == "theme: shipping under deadline"

    def test_content_change_invalidates(self, env) -> None:
        cache = get_theme_cache()
        v1 = "original content body"
        v2 = "edited content body — meaning changed"
        cache.put("n1", content_sha(v1), "theme line", "haiku")
        # The stored theme is keyed to v1's sha; v2's sha does not match.
        assert cache.get_valid("n1", content_sha(v2)) is None
        assert cache.has_valid("n1", content_sha(v1)) is True
        assert cache.has_valid("n1", content_sha(v2)) is False

    def test_missing_theme_returns_none(self, env) -> None:
        cache = get_theme_cache()
        assert cache.get_valid("never-themed", content_sha("x")) is None

    def test_missing_cache_file_graceful(self, env) -> None:
        # No put() has happened; get_valid on a fresh cache must not raise.
        cache = get_theme_cache()
        assert cache.get_valid("n1", content_sha("anything")) is None
        assert cache.count() == 0

    def test_stale_theme_composes_plain_content(self, env, monkeypatch) -> None:
        # Theme exists but content changed → lazy invalidation → plain content.
        monkeypatch.setenv("MEMCP_SEMANTIC_RECALL", "true")
        config_module._config = None
        cache = get_theme_cache()
        old = "the original node text"
        cache.put("n1", content_sha(old), "stale theme", "haiku")
        new = "the node text after an edit"
        assert compose_embedding_text("n1", new) == new


# ── Test 4 — composition ──────────────────────────────────────────────────────
class TestComposition:
    CONTENT = "Coordinated a cross-team launch fixer effort under a hard deadline."
    THEME = "themes: shipping-under-deadline; cross-team-coordination"

    def _seed_theme(self) -> None:
        get_theme_cache().put("n1", content_sha(self.CONTENT), self.THEME, "haiku")

    def test_flag_off_is_bit_identical_plain_content(self, env, monkeypatch) -> None:
        # Even with a valid theme present, flag OFF must return raw content —
        # bit-identical to the phase-3 embedding path.
        monkeypatch.setenv("MEMCP_SEMANTIC_RECALL", "false")
        config_module._config = None
        self._seed_theme()
        assert compose_embedding_text("n1", self.CONTENT) == self.CONTENT

    def test_flag_on_with_theme_includes_theme_line(self, env, monkeypatch) -> None:
        monkeypatch.setenv("MEMCP_SEMANTIC_RECALL", "true")
        config_module._config = None
        self._seed_theme()
        composed = compose_embedding_text("n1", self.CONTENT)
        assert composed != self.CONTENT
        assert composed.startswith(self.THEME)
        assert self.THEME in composed
        assert self.CONTENT[:EMBED_CONTENT_CHARS] in composed

    def test_flag_on_without_theme_is_plain_content(self, env, monkeypatch) -> None:
        monkeypatch.setenv("MEMCP_SEMANTIC_RECALL", "true")
        config_module._config = None
        # No theme seeded for this node.
        assert compose_embedding_text("unseen", self.CONTENT) == self.CONTENT

    def test_flag_on_truncates_long_content_after_theme(self, env, monkeypatch) -> None:
        monkeypatch.setenv("MEMCP_SEMANTIC_RECALL", "true")
        config_module._config = None
        long_content = "x" * (EMBED_CONTENT_CHARS + 500)
        get_theme_cache().put("big", content_sha(long_content), self.THEME, "haiku")
        composed = compose_embedding_text("big", long_content)
        # theme line + newline + exactly EMBED_CONTENT_CHARS of content.
        assert composed == f"{self.THEME}\n{long_content[:EMBED_CONTENT_CHARS]}"


# ── Persistence sanity ────────────────────────────────────────────────────────
class TestPersistence:
    def test_survives_reopen(self, env) -> None:
        path = config_module.get_config().cache_dir / "themes.sqlite"
        c1 = ThemeCache(path)
        c1.put("n1", content_sha("body"), "theme", "haiku")
        c1.close()
        c2 = ThemeCache(path)
        assert c2.get_valid("n1", content_sha("body")) == "theme"
        c2.close()
